name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libx11-dev

      - name: Build
        run: make

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./tokai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
